name: pybrainage_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn=0.24.2
  - pandas=1.3.4
  - numpy=1.20.3
  - matplotlib=3.4.2
  - seaborn=0.11.1
  - statsmodels=0.12.2
